// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, created_at, updated_at)
VALUES ($1, $2, NOW(), NOW())
RETURNING id, username, avatar_url, level, exp, rank_tier, rank_point, created_at, updated_at
`

type CreateUserParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	Username string      `db:"username" json:"username"`
}

// Creates a new user row for guest or Google login (D-14, D-12).
// UUID v7 PK generated by caller; timestamps set to NOW().
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.AvatarUrl,
		&i.Level,
		&i.Exp,
		&i.RankTier,
		&i.RankPoint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserProvider = `-- name: CreateUserProvider :one
INSERT INTO user_providers (id, user_id, provider, provider_user_id, email, created_at)
VALUES ($1, $2, $3, $4, $5, NOW())
RETURNING id, user_id, provider, provider_user_id, email, created_at
`

type CreateUserProviderParams struct {
	ID             pgtype.UUID `db:"id" json:"id"`
	UserID         pgtype.UUID `db:"user_id" json:"user_id"`
	Provider       string      `db:"provider" json:"provider"`
	ProviderUserID string      `db:"provider_user_id" json:"provider_user_id"`
	Email          *string     `db:"email" json:"email"`
}

// Inserts a new user_providers row for Google identity (D-10, D-12).
// created_at set to NOW(); no updated_at (insert-only table, D-11).
func (q *Queries) CreateUserProvider(ctx context.Context, arg CreateUserProviderParams) (UserProvider, error) {
	row := q.db.QueryRow(ctx, createUserProvider,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.Email,
	)
	var i UserProvider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const createWallet = `-- name: CreateWallet :exec
INSERT INTO wallets (user_id, coin_balance, gem_balance, updated_at)
VALUES ($1, 0, 0, NOW())
`

// Creates a wallets row for a newly registered user (guest or Google).
// DEC-013: wallet exclusively owns balance mutations; initial balances are 0.
func (q *Queries) CreateWallet(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, createWallet, userID)
	return err
}

const existsUsername = `-- name: ExistsUsername :one
SELECT EXISTS(SELECT 1 FROM users WHERE username = $1)::boolean AS exists
`

// Returns true if the given username is already taken (D-15: collision retry loop).
func (q *Queries) ExistsUsername(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, existsUsername, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, avatar_url, level, exp, rank_tier, rank_point, created_at, updated_at
FROM users
WHERE id = $1
`

// Fetches a single user by UUID; used after JWT validation to hydrate claims.
func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.AvatarUrl,
		&i.Level,
		&i.Exp,
		&i.RankTier,
		&i.RankPoint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProviderByProvider = `-- name: GetUserProviderByProvider :one
SELECT id, user_id, provider, provider_user_id, email, created_at
FROM user_providers
WHERE provider = $1 AND provider_user_id = $2
`

type GetUserProviderByProviderParams struct {
	Provider       string `db:"provider" json:"provider"`
	ProviderUserID string `db:"provider_user_id" json:"provider_user_id"`
}

// Looks up an existing provider record for Google login deduplication (D-12).
func (q *Queries) GetUserProviderByProvider(ctx context.Context, arg GetUserProviderByProviderParams) (UserProvider, error) {
	row := q.db.QueryRow(ctx, getUserProviderByProvider, arg.Provider, arg.ProviderUserID)
	var i UserProvider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
