// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InventoryItem struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	ItemID    pgtype.UUID        `db:"item_id" json:"item_id"`
	Equipped  bool               `db:"equipped" json:"equipped"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Match struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Mode       string             `db:"mode" json:"mode"`
	Status     string             `db:"status" json:"status"`
	Difficulty string             `db:"difficulty" json:"difficulty"`
	PuzzleID   pgtype.UUID        `db:"puzzle_id" json:"puzzle_id"`
	StakeCoin  int64              `db:"stake_coin" json:"stake_coin"`
	StartedAt  pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt    pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type MatchMove struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	MatchID    pgtype.UUID        `db:"match_id" json:"match_id"`
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	RowIndex   int16              `db:"row_index" json:"row_index"`
	ColIndex   int16              `db:"col_index" json:"col_index"`
	Value      int16              `db:"value" json:"value"`
	IsCorrect  bool               `db:"is_correct" json:"is_correct"`
	ScoreDelta int32              `db:"score_delta" json:"score_delta"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type MatchPlayer struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	MatchID    pgtype.UUID        `db:"match_id" json:"match_id"`
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	Score      int32              `db:"score" json:"score"`
	Progress   int32              `db:"progress" json:"progress"`
	Combo      int32              `db:"combo" json:"combo"`
	WrongCount int32              `db:"wrong_count" json:"wrong_count"`
	HintUsed   int32              `db:"hint_used" json:"hint_used"`
	Result     *string            `db:"result" json:"result"`
	CoinChange *int64             `db:"coin_change" json:"coin_change"`
	RankChange *int32             `db:"rank_change" json:"rank_change"`
	FinishedAt pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
}

type Mission struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	Type        string      `db:"type" json:"type"`
	Name        string      `db:"name" json:"name"`
	Description *string     `db:"description" json:"description"`
	TargetValue int32       `db:"target_value" json:"target_value"`
	RewardCoin  int64       `db:"reward_coin" json:"reward_coin"`
	RewardExp   int32       `db:"reward_exp" json:"reward_exp"`
	IsActive    bool        `db:"is_active" json:"is_active"`
}

type ShopItem struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	Type      string      `db:"type" json:"type"`
	Name      string      `db:"name" json:"name"`
	CoinPrice *int64      `db:"coin_price" json:"coin_price"`
	GemPrice  *int64      `db:"gem_price" json:"gem_price"`
	Metadata  []byte      `db:"metadata" json:"metadata"`
	IsActive  bool        `db:"is_active" json:"is_active"`
}

type SudokuPuzzle struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Difficulty   string             `db:"difficulty" json:"difficulty"`
	PuzzleGrid   []byte             `db:"puzzle_grid" json:"puzzle_grid"`
	SolutionGrid []byte             `db:"solution_grid" json:"solution_grid"`
	EmptyCount   int32              `db:"empty_count" json:"empty_count"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Username  string             `db:"username" json:"username"`
	AvatarUrl *string            `db:"avatar_url" json:"avatar_url"`
	Level     int32              `db:"level" json:"level"`
	Exp       int32              `db:"exp" json:"exp"`
	RankTier  string             `db:"rank_tier" json:"rank_tier"`
	RankPoint int32              `db:"rank_point" json:"rank_point"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserMission struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
	MissionID pgtype.UUID `db:"mission_id" json:"mission_id"`
	Progress  int32       `db:"progress" json:"progress"`
	Claimed   bool        `db:"claimed" json:"claimed"`
}

type UserProvider struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	UserID         pgtype.UUID        `db:"user_id" json:"user_id"`
	Provider       string             `db:"provider" json:"provider"`
	ProviderUserID string             `db:"provider_user_id" json:"provider_user_id"`
	Email          *string            `db:"email" json:"email"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Wallet struct {
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	CoinBalance int64              `db:"coin_balance" json:"coin_balance"`
	GemBalance  int64              `db:"gem_balance" json:"gem_balance"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type WalletTransaction struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	UserID        pgtype.UUID        `db:"user_id" json:"user_id"`
	Type          string             `db:"type" json:"type"`
	Amount        int64              `db:"amount" json:"amount"`
	BalanceBefore int64              `db:"balance_before" json:"balance_before"`
	BalanceAfter  int64              `db:"balance_after" json:"balance_after"`
	ReferenceType *string            `db:"reference_type" json:"reference_type"`
	ReferenceID   *string            `db:"reference_id" json:"reference_id"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
