// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Creates a new user row for guest or Google login (D-14, D-12).
	// UUID v7 PK generated by caller; timestamps set to NOW().
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Inserts a new user_providers row for Google identity (D-10, D-12).
	// created_at set to NOW(); no updated_at (insert-only table, D-11).
	CreateUserProvider(ctx context.Context, arg CreateUserProviderParams) (UserProvider, error)
	// Creates a wallets row for a newly registered user (guest or Google).
	// DEC-013: wallet exclusively owns balance mutations; initial balances are 0.
	CreateWallet(ctx context.Context, userID pgtype.UUID) error
	// Returns true if the given username is already taken (D-15: collision retry loop).
	ExistsUsername(ctx context.Context, username string) (bool, error)
	// Fetches a single user by UUID; used after JWT validation to hydrate claims.
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	// Looks up an existing provider record for Google login deduplication (D-12).
	GetUserProviderByProvider(ctx context.Context, arg GetUserProviderByProviderParams) (UserProvider, error)
}

var _ Querier = (*Queries)(nil)
