-- name: CreateUser :one
-- Creates a new user row for guest or Google login (D-14, D-12).
-- UUID v7 PK generated by caller; timestamps set to NOW().
INSERT INTO users (id, username, created_at, updated_at)
VALUES ($1, $2, NOW(), NOW())
RETURNING id, username, avatar_url, level, exp, rank_tier, rank_point, created_at, updated_at;

-- name: CreateUserProvider :one
-- Inserts a new user_providers row for Google identity (D-10, D-12).
-- created_at set to NOW(); no updated_at (insert-only table, D-11).
INSERT INTO user_providers (id, user_id, provider, provider_user_id, email, created_at)
VALUES ($1, $2, $3, $4, $5, NOW())
RETURNING id, user_id, provider, provider_user_id, email, created_at;

-- name: GetUserProviderByProvider :one
-- Looks up an existing provider record for Google login deduplication (D-12).
SELECT id, user_id, provider, provider_user_id, email, created_at
FROM user_providers
WHERE provider = $1 AND provider_user_id = $2;

-- name: GetUserByID :one
-- Fetches a single user by UUID; used after JWT validation to hydrate claims.
SELECT id, username, avatar_url, level, exp, rank_tier, rank_point, created_at, updated_at
FROM users
WHERE id = $1;

-- name: ExistsUsername :one
-- Returns true if the given username is already taken (D-15: collision retry loop).
SELECT EXISTS(SELECT 1 FROM users WHERE username = $1)::boolean AS exists;

-- name: CreateWallet :exec
-- Creates a wallets row for a newly registered user (guest or Google).
-- DEC-013: wallet exclusively owns balance mutations; initial balances are 0.
INSERT INTO wallets (user_id, coin_balance, gem_balance, updated_at)
VALUES ($1, 0, 0, NOW());
